[package]
name = "wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
nom-supreme = "0.6"
wasm-derive = {path = "../wasm-derive"}
wasm-core = {path = "../wasm-core"}